name: books_sdk
description: A Very Good Project created by Very Good CLI.
version: 0.1.0+1
publish_to: none

environment:
  sdk: ^3.4.0

dependencies:
  chopper: ^8.0.1+1
  json_annotation: ^4.9.0

dev_dependencies:
  build_runner: ^2.4.9
  chopper_generator: ^8.0.1
  json_serializable: ^6.8.0
  mocktail: ^1.0.3
  test: ^1.25.2
  very_good_analysis: ^6.0.0
